# Generated by Django 5.0.2 on 2024-02-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('serialno', models.IntegerField(primary_key=True, serialize=False)),
                ('booklanguage', models.CharField(max_length=20)),
                ('bookauthor', models.CharField(max_length=20)),
                ('editionno', models.IntegerField()),
                ('duedate', models.DateField()),
            ],
        ),
    ]
